PIC_IOBASE	EQU	40h
UART_D8251	EQU	0
UART_C8251	EQU	1
;
;	SuperMEZ80 I/O ports (PIC)

DRV_NO		EQU	0FB20H
TRK_NO		EQU	0FB21H
SEC_NO		EQU	0FB22H
DMA_L		EQU	0FB23H
DMA_H		EQU	0FB24H

GET_BDOSCCP	EQU	PIC_IOBASE+6	;load bdos+ccp from pic rom
GET_BIOS	EQU	PIC_IOBASE+7	;load bios from pic rom

FDCST		EQU	PIC_IOBASE+14	;fdc-port: status
DISK_READ	EQU	PIC_IOBASE+18
DISK_WRITE	EQU	PIC_IOBASE+19
D_SUCCESS	EQU	0
D_ERROR		EQU	1

IOBASE_180	EQU	0C0H

